version: "1.0"
services:
        mariadb:
                container_name: mariadb
                hostname: mariadb_server
                image: "mariadb_image"
                init: true
                restart: always
                build: "./requirements/mariadb"
                environment:
                        - DB_NAME=${DB_NAME}
                        - USER=${USER}
                        - USER_PASSWORD=${USER_PASSWORD}
                        - ADMIN=${ADMIN}
                        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
                networks:
                        - my-network
                volumes:
                        - /home/yakhoudr/data/mariadb/wordpress_db:/var/lib/mysql/${DB_NAME}
        wordpress:
                container_name: wordpress
                init: true
                hostname: php_fpm_server
                image: "wordpress_image"
                restart: always
                build: "./requirements/wordpress"
                depends_on:
                        - mariadb
                environment:
                        - DB_NAME=${DB_NAME}
                        - USER=${USER}
                        - USER_PASSWORD=${USER_PASSWORD}
                        - DB_HOST=${DB_HOST}
                        - WORD_ADMIN=${WORD_ADMIN}
                        - WORD_ADMIN_PASSWORD=${WORD_ADMIN_PASSWORD}
                        - WORD_ADMIN_EMAIL=${WORD_ADMIN_EMAIL}
                networks:
                        - my-network
                volumes:
                        - /home/yakhoudr/data/wordpress:/var/www/Inception-website
networks:
        my-network:
                driver: bridge
