version: "1.0"
services:
        mariadb:
                init: true
                container_name: mariadb
                hostname: ${DB_HOST}
                image: "mariadb_image"
                restart: always
                build: "./requirements/mariadb"
                environment:
                        - DB_NAME=${DB_NAME}
                        - USER=${USER}
                        - USER_PASSWORD=${USER_PASSWORD}
                        - ADMIN=${ADMIN}
                        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
                networks:
                        - database-network
                healthcheck:
                        test: ["CMD", "mysqladmin", "ping", "-h" ,"localhost"]
                        interval: 5s
                        timeout: 0s
                        retries: 5
                volumes:
                        - database-volume:/var/lib/mysql/${DB_NAME}
        wordpress:
                init: true
                container_name: wordpress
                hostname: php_fpm_server
                image: "wordpress_image"
                restart: always
                build: "./requirements/wordpress"
                depends_on:
                        mariadb:
                                condition: service_healthy
                environment:
                        - DB_NAME=${DB_NAME}
                        - USER=${USER}
                        - USER_PASSWORD=${USER_PASSWORD}
                        - DB_HOST=${DB_HOST}
                        - WORD_ADMIN=${WORD_ADMIN}
                        - WORD_ADMIN_PASSWORD=${WORD_ADMIN_PASSWORD}
                        - WORD_ADMIN_EMAIL=${WORD_ADMIN_EMAIL}
                        - WORD_USER=${WORD_USER}
                        - WORD_USER_PASS=${WORD_USER_PASS}
                        - WORD_USER_EMAIL=${WORD_USER_EMAIL}
                        - WORD_USER_ROLE=${WORD_USER_ROLE}
                networks:
                        - database-network
                        - webserver-network
                        - redis-network
                volumes:
                        - wordpress-volume:/var/www/Inception-website
                healthcheck:
                        test: ["CMD", "pidof", "php-fpm7.4", ">/dev/null"]
                        interval: 5s
                        timeout: 0s
                        retries: 30

        redis:
                init: true
                container_name: redis
                hostname: redis_server
                image: "redis_image"
                restart: always
                build: "./requirements/bonus/redis"
                depends_on:
                        wordpress:
                                condition: service_started
                networks:
                        - redis-network
        nginx:
                init: true
                container_name: nginx
                hostname: nginx_server
                image: "nginx_image"
                restart: always
                build: "./requirements/nginx"
                depends_on:
                        wordpress:
                                condition: service_healthy
                networks:
                        - webserver-network
                ports:
                        - 443:443
                volumes:
                        - wordpress-volume:/var/www/Inception-website:ro
        ftp:
                init: true
                container_name: ftp
                image: "ftp_image"
                environment:
                        - FTP_USER=${FTP_USER}
                        - FTP_PASS=${FTP_PASS}
                restart: always
                build: "./requirements/bonus/ftp"
                depends_on:
                        - wordpress
                ports:
                        - 21:21
                volumes:
                        - wordpress-volume:/home/${FTP_USER}
        adminer:
                init: true
                hostname: adminer
                container_name: adminer
                image: "adminer_image"
                restart: always
                depends_on:
                        - wordpress
                build: "./requirements/bonus/adminer"
                networks:
                        - database-network
                ports:
                        - 7000:7000
        simple_website:
                init: true
                container_name: simple_website
                image: "simple_website"
                restart: always
                build: "./requirements/bonus/simple_website"
                ports:
                        - 80:80
        portainer:
                init: true
                container_name: portainer
                image: "portainer"
                restart: always
                build: "./requirements/bonus/portainer"
                ports:
                        - 9000:9000
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock

networks:
        database-network:
        webserver-network:
        redis-network:
volumes:
        wordpress-volume:
                driver: local
                driver_opts:
                        type: none
                        device: /home/yakhoudr/data/wordpress
                        o: bind
        database-volume:
                driver: local
                driver_opts:
                        type: none
                        device: /home/yakhoudr/data/mariadb
                        o: bind
