version: "1.0"
services:
        mariadb:
                init: true
                container_name: mariadb
                hostname: ${DB_HOST}
                image: "mariadb_image"
                restart: always
                build: "./requirements/mariadb"
                environment:
                        - DB_NAME=${DB_NAME}
                        - USER=${USER}
                        - USER_PASSWORD=${USER_PASSWORD}
                        - ADMIN=${ADMIN}
                        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
                networks:
                        - database-network
                volumes:
                        - "~/data/mariadb/db:/var/lib/mysql/${DB_NAME}:shared"
                healthcheck:
                        test: ["CMD", "mysqladmin", "ping", "-h" ,"localhost"]
                        interval: 15s
                        timeout: 10s
                        retries: 1
        wordpress:
                init: true
                container_name: wordpress
                hostname: php_fpm_server
                image: "wordpress_image"
                restart: always
                build: "./requirements/wordpress"
                depends_on:
                        mariadb:
                                condition: service_healthy
                environment:
                        - DB_NAME=${DB_NAME}
                        - USER=${USER}
                        - USER_PASSWORD=${USER_PASSWORD}
                        - DB_HOST=${DB_HOST}
                        - WORD_ADMIN=${WORD_ADMIN}
                        - WORD_ADMIN_PASSWORD=${WORD_ADMIN_PASSWORD}
                        - WORD_ADMIN_EMAIL=${WORD_ADMIN_EMAIL}
                        - WORD_USER=${WORD_USER}
                        - WORD_USER_PASS=${WORD_USER_PASS}
                        - WORD_USER_EMAIL=${WORD_USER_EMAIL}
                        - WORD_USER_ROLE=${WORD_USER_ROLE}
                networks:
                        - database-network
                        - webserver-network
                        - redis-network
                volumes:
                        - "~/data/wordpress:/var/www/Inception-website:shared"

        redis:
                init: true
                container_name: redis
                hostname: redis_server
                image: "redis_image"
                restart: always
                build: "./requirements/bonus/redis"
                depends_on:
                        wordpress:
                                condition: service_started
                networks:
                        - redis-network
        nginx:
                init: true
                container_name: nginx
                hostname: nginx_server
                image: "nginx_image"
                restart: always
                build: "./requirements/nginx"
                depends_on:
                        - wordpress
                networks:
                        - webserver-network
                volumes:
                        - "~/data/wordpress:/var/www/Inception-website:ro"
                ports:
                        - 443:443
        ftp:
                init: true
                container_name: ftp
                image: "ftp_image"
                environment:
                        - FTP_USER=${FTP_USER}
                        - FTP_PASS=${FTP_PASS}
                restart: always
                build: "./requirements/bonus/ftp"
                depends_on:
                        - wordpress
                volumes:
                        - "~/data/wordpress:/home/${FTP_USER}:shared"
                ports:
                        - 21:21
        adminer:
                init: true
                hostname: adminer
                container_name: adminer
                image: "adminer_image"
                restart: always
                depends_on:
                        - wordpress
                build: "./requirements/bonus/adminer"
                networks:
                        - database-network
                ports:
                        - 7000:7000
        simple_website:
                init: true
                container_name: simple_website
                image: "simple_website"
                restart: always
                build: "./requirements/bonus/simple_website"
                ports:
                        - 80:80
networks:
        database-network:
        webserver-network:
        redis-network:
