version: "1.0"
services:
        mariadb:
                container_name: mariadb
                hostname: ${DB_HOST}
                image: "mariadb_image"
                init: true
                restart: always
                build: "./requirements/mariadb"
                environment:
                        - DB_NAME=${DB_NAME}
                        - USER=${USER}
                        - USER_PASSWORD=${USER_PASSWORD}
                        - ADMIN=${ADMIN}
                        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
                networks:
                        - database-network
                volumes:
                        - "~/data/mariadb/${DB_NAME}:/var/lib/mysql/${DB_NAME}:rw, shared"

        wordpress:
                container_name: wordpress
                init: true
                hostname: php_fpm_server
                image: "wordpress_image"
                restart: always
                build: "./requirements/wordpress"
                depends_on:
                        - mariadb
                environment:
                        - DB_NAME=${DB_NAME}
                        - USER=${USER}
                        - USER_PASSWORD=${USER_PASSWORD}
                        - DB_HOST=${DB_HOST}
                        - WORD_ADMIN=${WORD_ADMIN}
                        - WORD_ADMIN_PASSWORD=${WORD_ADMIN_PASSWORD}
                        - WORD_ADMIN_EMAIL=${WORD_ADMIN_EMAIL}
                        - WORD_USER=${WORD_USER}
                        - WORD_USER_PASS=${WORD_USER_PASS}
                        - WORD_USER_EMAIL=${WORD_USER_EMAIL}
                        - WORD_USER_ROLE=${WORD_USER_ROLE}
                networks:
                        - database-network
                        - webserver-network
                volumes:
                        - "~/data/wp:/var/www/Inception-website:rw, shared"

        nginx:
                container_name: nginx
                init: true
                hostname: nginx_server
                image: "nginx_image"
                restart: always
                build: "./requirements/nginx"
                depends_on:
                        - wordpress
                        - mariadb
                networks:
                        - webserver-network
                ports:
                        - 443:443
                volumes:
                        - "~/data/wp:/var/www/Inception-website:rw, shared"
networks:
        database-network:
        webserver-network:
